# Generated by Django 4.1.7 on 2023-04-14 20:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='datosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(default='ANOMIMO', max_length=32)),
                ('apellidoUsuario', models.CharField(default='ANONIMO', max_length=32)),
                ('emailUsuario', models.CharField(default='', max_length=25)),
                ('userNameUsuario', models.CharField(default='', max_length=15)),
                ('contrasenaUsuario', models.CharField(default='', max_length=32)),
                ('rolUsuario', models.CharField(default='', max_length=512)),
                ('numCelularUsuario', models.CharField(max_length=9)),
                ('fechIngresoUsuario', models.DateField(default=datetime.date.today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
